@startuml vp1
actor Actor as actor
participant SistemaRobDroneGO as srdg <<System(C4)>>

activate actor
actor -> srdg: Editar edificio
activate srdg
alt 
srdg --> actor : ok
else
srdg --> actor : erro
end
deactivate srdg
deactivate actor
@enduml