@startuml vp3
participant View as view
participant Controller as ctrl
participant Service as svc
participant Passagem as model
participant MDGD as be

activate view
view -> ctrl : updatePassagem()
activate ctrl
ctrl -> model : updatePassagem(designacao, edificioA, edificioB, pisoA, pisoB)
activate model
model --> ctrl : passagem
deactivate model
ctrl -> svc: save(passagem)
activate svc
svc -> be: PUT passagem {json}
activate be
be --> svc : Resposta HTTP
deactivate be
alt sucesso 
svc --> ctrl : HTTP 200
ctrl --> view : Envia Mensagem
else insucesso
svc --> ctrl : HTTP 4xx / HTTP500
ctrl --> view : Envia Mensagem
end
deactivate view
deactivate ctrl
@enduml