@startuml getPackagingSD

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

box "<<System(C4)>>\n SistemaRobDroneGo"
participant Visualization as ui <<Container(C4)>>
participant AuthorizationAuthentication as mdl <<Container(C4)>>
ui -> mdl: PATCH aprovaUtente(aprovação/recusa)
alt não existe erros durante a operação
mdl --> ui: 200 utente aprovado/recusado
else existe erros durante a operação
mdl --> ui: 403 falha na aprovação/recusa
end 

end box

@enduml