@startuml
actor Utente as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Cópia dos dados pessoais
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml