@startuml vp1
actor "Utente" as actor
participant SistemaRobDroneGO as srdg <<System(C4)>>

activate actor
actor -> srdg: Requisitar tarefa
activate srdg
alt 
srdg --> actor : ok
else
srdg --> actor : erro
end
deactivate srdg
deactivate actor
@enduml