@startuml getPackagingSD

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

box "<<System(C4)>>\n SistemaRobDroneGo"
participant UI as ui <<Container(C4)>>
participant "Master Data Gestão Tarefas" as mdgt <<Container(C4)>>
activate ui
ui -> mdgt: POST /rejeitarRequisicao(corpo)
activate mdgt
alt sucesso
mdgt --> ui: devolve status 201
else erro na listagem
mdgt --> ui: devolve status 403
deactivate mdgt
end 
deactivate ui

end box

@enduml