@startuml vp1

actor "Gestor de Frota" as actor
participant SistemaRobDroneGO as srdg <<System(C4)>>

activate actor
actor -> srdg: Consultar todos os robos da frota
activate srdg
alt 
srdg --> actor : ok
else
srdg --> actor : erro
end
deactivate srdg
deactivate actor
@enduml