@startuml vp3

participant Component as comp
participant RoboService as svc
participant Model as model
participant MDGD as mdgd

activate comp
comp -> model : adapta dados introduzidos 
activate model
model --> comp
deactivate model
comp -> svc : getRobo(elevador)
activate svc
svc -> mdgd : pedido HTTP GET de robos
activate mdgd
mdgd --> svc
deactivate mdgd
svc --> comp
deactivate svc
deactivate comp

@enduml