@startuml vp3
participant View as view
participant Controller as ctrl
participant Service as svc
participant Passagem as model
participant MDGD as be

activate view
view -> ctrl : listPisosPassagem()
activate ctrl
ctrl -> model : listPisosPassagem()
activate model
model --> ctrl : pisos
deactivate model
ctrl -> svc: get(pisos)
activate svc
svc -> be: GET piso[] {json}
activate be
be --> svc : Resposta HTTP
deactivate be
alt sucesso 
svc --> ctrl : HTTP 200
ctrl --> view : Envia Mensagem
else insucesso
svc --> ctrl : HTTP 4xx / HTTP500
ctrl --> view : Envia Mensagem
end
deactivate view
deactivate ctrl
@enduml