@startuml getPackagingSD

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

box "<<System(C4)>>\n SistemaRobDroneGo"
participant Visualization as ui <<Container(C4)>>
participant MDGD as mdl <<Container(C4)>>
ui -> mdl: GET getEdificios()
alt não existe erros durante a operação
mdl --> ui: 200 envia lista de edficios
else existe erros durante a operação
mdl --> ui: 403 não existem edificios registados
end 

end box

@enduml