@startuml sd


participant RoboRoute as route
participant InterfaceRoboController as ictrl
participant RoboController as ctrl
participant InterfaceRoboService as isvc
participant RoboService as svc
participant InterfaceRoboRepo as irepo

participant InterfaceTipoRoboRepo as ierepo
participant RoboRepo as repo

participant TipoRoboRepo as erepo
participant RoboMapper as mapper

participant TipoRoboMapper as emapper
participant InterfaceRoboPersistence as ischema

participant InterfaceTipoRoboPersistence as ieschema
participant RoboSchema as schema

participant TipoRoboSchema as eschema
participant ConfigurationFile as conf



route -> ictrl++ : createRobo(req,res,next)
route++
ictrl -> ctrl : createRobo(req,res,next)
ctrl++
ctrl -> conf : injeta o serviço do robo
conf++
conf --> ctrl
conf--
ctrl -> isvc : createRobo(roboDTO)
isvc++
isvc -> svc : createRobo(roboDTO)
svc++
svc -> conf : injeta o repositório do robo
conf++
conf --> svc
conf--
svc -> conf : injeta o repositório do tipoRobo
conf++
conf --> svc
conf--


svc -> irepo : findByCodigo(codigo)
irepo++
irepo -> repo : findByCodigo(codigo)
repo++
repo -> conf : injeta o schema do robo
conf++
conf --> repo
conf--
repo -> ischema : findOne(query)
ischema++
ischema -> schema : findOne(query)
schema++
schema --> ischema
schema--
ischema --> repo
ischema--
repo -> mapper : toDomain(roboRecord)
mapper++
mapper --> repo
mapper--
repo--> irepo
repo--
irepo --> svc




svc -> ierepo : findByDesignacao(tipoRoboDTO)
ierepo++
ierepo -> erepo : findByDesignacao(tipoRoboDTO)
erepo++
erepo -> conf : injeta o schema do tipoRobo
conf++
conf --> erepo
conf--
erepo -> ieschema : findOne(query)
ieschema++
ieschema -> eschema : findOne(query)
eschema++
eschema --> ieschema
eschema--
ieschema --> erepo
ieschema--
erepo -> emapper : toDomain(tipoRoboRecord)
emapper++
emapper --> erepo
emapper--
erepo--> ierepo
erepo--
ierepo --> svc
ierepo--

svc -> model : create()
model++
model --> svc
model--
svc -> irepo: save(robo)
irepo -> repo :save(robo)
repo++
repo -> ischema : findOne(query)
ischema++
ischema -> schema : findOne(query)
schema++
schema --> ischema
schema--
ischema --> repo
alt cria robo
repo -> mapper : toPersistence(robo)
mapper++
mapper --> repo
mapper--
repo -> ischema : create(rawRobo)
ischema -> schema : create(rawRobo)
schema++
schema --> ischema
schema--
ischema --> repo
ischema--
repo -> mapper : toDomain(roboCreated)
mapper++
mapper --> repo
mapper--
else atualiza robo
end
repo --> irepo
repo--
irepo --> svc
irepo--
svc -> mapper : toDTO(roboResult)
mapper++
mapper --> svc
mapper--
svc --> isvc 
svc--
isvc --> ctrl
isvc--
ctrl --> ictrl

alt caso de sucesso
    ctrl --> ictrl : Envia um código 201 (POST)
else caso de insucesso
    ctrl --> ictrl : Envia um código 403 (NOT FOUND)
    ctrl--
end

ictrl --> route
ictrl--
