@startuml
actor GestorCampus as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Editar edificio
srdg --> actor : Requesita dados
actor -> srdg: Envia dados de edificio
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml