@startuml vp1
actor GestorCampus as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Editar Passagem entre edificios
srdg --> actor : Requesita dados
actor -> srdg: Envia dados da passagem
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml