@startuml
actor Administrador as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Criar utilizador
srdg --> actor : Requesita dados
actor -> srdg: Envia dados de utilizador
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml