@startuml
actor GestorCampus as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Listar edificios
srdg --> actor : Requesita dados
actor -> srdg: Envia lista de edificios
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml