@startuml vp1
actor GestorCampus as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Listar Pisos
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml