@startuml sd

participant Route as route
participant InterfaceEdificioController as ictrl
participant EdificioController as ctrl
participant InterfaceEdificioService as isvc
participant EdificioService as svc
participant InterfaceEdificioRepo as irepo
participant EdificioRepo as repo
participant EdificioMapper as mapper
participant InterfaceEdificioPersistence as ischema
participant EdificioSchema as schema
participant ConfigurationFile as conf
participant Edificio as model

activate route
route -> ictrl : criar edificio
activate ictrl
ictrl -> ctrl : createEdificio(req, res, next)
activate ctrl
ctrl -> conf : injeta o serviço do edificio
activate conf
conf --> ctrl
deactivate conf
ctrl -> isvc : createEdificio(IEdificioDTO)
activate isvc
isvc -> svc : createEdificio(IEdificioDTO)
activate svc
svc -> conf : injeta o repositório do edificio
activate conf
conf --> svc
deactivate conf
svc -> model : edificio = create(edificioDTO)
activate model
model --> svc
deactivate model
svc -> irepo : edificio = save(edificio)
activate irepo
irepo -> repo : save(edificio)
activate repo
repo -> conf : injeta o schema do edificio
activate conf
conf --> repo
deactivate conf
repo -> mapper : toPersistence(edificio)
activate mapper
mapper --> repo
deactivate mapper
repo -> ischema : create(edificioCreated)
activate ischema 
ischema -> schema : create(edificioCreated)
activate schema
schema --> ischema
deactivate schema
deactivate schema
ischema --> repo
deactivate ischema
repo -> mapper : toDomain(edificioCreated)
activate mapper
mapper --> repo
deactivate mapper
repo --> irepo
deactivate repo
irepo --> svc
deactivate irepo
svc -> mapper : toDTO(edificio)
activate mapper
mapper --> svc
deactivate mapper
svc --> isvc
deactivate svc
isvc --> ctrl
deactivate isvc
alt caso de sucesso
    ctrl --> ictrl : Envia um código 201 (POST)
else caso de insucesso
    ctrl --> ictrl : Envia um código 404 (NOT FOUND)
end
deactivate ctrl
ictrl --> route
deactivate ictrl
deactivate route



@enduml