@startuml
actor Utente as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Alterar dados de utente
srdg --> actor : Requesita dados
actor -> srdg: Envia dados
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml