@startuml vp2

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

box "<<System(C4)>>\n SistemaRobDroneGo"
participant Visualization as ui <<Container(C4)>>
participant MDGD as mdl <<Container(C4)>>
ui -> mdl: POST criarSala(descricao,categoria,designacao,piso)
alt não existe erros durante a operação
mdl --> ui: 200 sala craida com sucesso
else existe erros durante a operação
mdl --> ui: 403 não foi possivel criar sala
end 

end box

@enduml