@startuml ed190

hide circle
hide fields

!theme crt-green
skinparam nodesep 150
hide empty members
left to right direction

package "<<agr Piso>>"{
    class Piso<<entity>><<root>>{}
    class DesignacaoPiso<<vo>>{}
    class DescricaoPiso<<vo>>{}

    Sala --> "1" Piso

    Piso --> "1" DesignacaoPiso
    Piso --> "1" DescricaoPiso
}

'o código do edificio é obrigatório, no máximo 5 caracteres, letras e digitos, podendo conter espaços no meio
'o nome do edificio é opcional, no máximo 50 caracteres alfanuméricos
package "<<agr Edificio>>"{
    class Edificio<<entity>><<root>>{}
    class CodigoEdificio<<vo>>{}
    class NomeOpcionalEdificio<<vo>>{}
    class DescricaoEdificio<<vo>>{}
    class DimensaoMaximaPiso<<vo>>{}
    note right{
        dimensão máxima de cada piso em termos de células (ex., 10 x 10)
    }

    Elevador --> "1" Edificio
    Piso --> "1" Edificio : "está contido"

    Edificio --> "1" CodigoEdificio
    Edificio --> "1" NomeOpcionalEdificio
    Edificio --> "1" DescricaoEdificio
    Edificio --> "1" DimensaoMaximaPiso
}

@enduml