@startuml
actor GestorFrota as actor
participant SistemaRobDroneGo as srdg
actor -> srdg: Adicionar Robo
srdg --> actor : Requesita dados
actor -> srdg: Envia dados do robo
alt sucesso
srdg --> actor : Mensagem de Sucesso
else insucesso
srdg -->actor : Mensagem de Erro
end
@enduml