@startuml vp2

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

box "<<System(C4)>>\n SistemaRobDroneGo"
participant UI as ui <<Container(C4)>>
participant MasterDataGestaoDispositivos as mdl <<Container(C4)>>
activate ui
ui -> mdl: POST /createTipoRobo(corpo)
activate mdl
alt sucesso
mdl --> ui: devolve status 201
else erro na listagem
mdl --> ui: devolve status 403
deactivate mdl
end 
deactivate ui

end box

@enduml