@startuml vp3


participant Route as route
participant "A&A" as auth
participant TarefaAprovacaoController as ctrl
participant TarefaAprovacaoService as svc
participant "Master Data Gestão de Tarefas" as mdgt

activate route
route -> auth : autentica("Utente")
activate auth
auth --> route
deactivate auth
route -> ctrl : /requisitar
activate ctrl
ctrl -> svc : requisitar()
activate svc
svc -> mdgt : POST /requisitar
activate mdgt 
mdgt --> svc
deactivate mdgt
svc --> ctrl
deactivate svc
ctrl --> route : Envia um código 201 (OK) / 403 (FORBIDDEN)
deactivate ctrl
deactivate route



@enduml