@startuml vp1
actor "Gestor de Tarefas" as actor
participant SistemaRobDroneGO as srdg <<System(C4)>>

activate actor
actor -> srdg: pesquisar as requisições de tarefas por estado, por tipo de dispositivo, ou utente
activate srdg
alt 
srdg --> actor : ok
else
srdg --> actor : erro
end
deactivate srdg
deactivate actor
@enduml