@startuml vp3
participant View as view
participant Controller as ctrl
participant Service as svc
participant Piso as model
participant MDGD as be

activate view
view -> ctrl : createPiso()
activate ctrl
ctrl -> model : createPiso(descricao,designacao,edificio)
activate model
model --> ctrl : piso
deactivate model
ctrl -> svc: save(piso)
activate svc
svc -> be: POST piso {json}
activate be
be --> svc : Resposta HTTP
deactivate be
alt sucesso 
svc --> ctrl : HTTP 200
ctrl --> view : Envia Mensagem
else insucesso
svc --> ctrl : HTTP 4xx / HTTP500
ctrl --> view : Envia Mensagem
end
deactivate view
deactivate ctrl
@enduml