@startuml getPackagingSD

skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor white
}

box "<<System(C4)>>\n SistemaRobDroneGo"
participant Visualization as ui <<Container(C4)>>
participant MDGD as mdl <<Container(C4)>>
ui -> mdl: PUT updateEdificio(codigoEdificio,descricaoEdificio,dimensaoMaximaPiso,nomeOpcionalEdificio,mapaPiso)
alt não existe erros durante a operação
mdl --> ui: 200 edificio editado
else existe erros durante a operação
mdl --> ui: 403 não foi possivel editar edificio
end 

end box

@enduml