@startuml vp1
actor "GestorUtilizadores" as actor
participant SistemaRobDroneGO as srdg <<System(C4)>>

activate actor
actor -> srdg: Criar User
activate srdg
alt 
srdg --> actor : ok (201)
else
srdg --> actor : erro (403)
end
deactivate srdg
deactivate actor
@enduml