@startuml sd

participant Route as route
participant InterfaceElevadorController as ictrl
participant ElevadorController as ctrl
participant InterfaceElevadorService as isvc
participant ElevadorService as svc
participant InterfaceElevadorRepo as irepo
participant ElevadorRepo as repo
participant ElevadorMapper as mapper
participant InterfaceElevadorPersistence as ischema
participant ElevadorSchema as schema
participant ConfigurationFile as conf
participant Elevador as model

activate route
route -> ictrl : /updateElevador
activate ictrl
ictrl -> ctrl : updateElevador(req, res, next)
activate ctrl
ctrl -> conf : injeta o serviço do elevador
activate conf
conf --> ctrl
deactivate conf
ctrl -> isvc : updateElevador(IElevadorDTO)
activate isvc
isvc -> svc : updateElevador(IElevadorDTO)
activate svc
svc -> conf : injeta o repositório do elevador
activate conf
conf --> svc
deactivate conf
svc -> repo : elevador = findByDomainId(id)
activate repo
repo --> svc
deactivate repo
alt elevador não existe
    svc --> isvc : Elevador não encontrado
    isvc --> ctrl
    ctrl --> ictrl : Envia um código 404 (NOT FOUND)
    ictrl --> route
end
svc -> model : elevador atualiza os campos
activate model
model --> svc
deactivate model
svc -> irepo : elevador = save(elevador)
activate irepo
irepo -> repo : save(elevador)
activate repo
repo -> conf : injeta o schema do elevador
activate conf
conf --> repo
deactivate conf
repo -> mapper : toPersistence(elevador)
activate mapper
mapper --> repo
deactivate mapper
repo -> ischema : create(elevadorCreated)
activate ischema 
ischema -> schema : create(elevadorCreated)
activate schema
schema --> ischema
deactivate schema
ischema --> repo
deactivate ischema
repo -> mapper : toDomain(elevadorCreated)
activate mapper
mapper --> repo
deactivate mapper
repo --> irepo
deactivate repo
irepo --> svc
deactivate irepo
svc -> mapper : toDTO(elevador)
activate mapper
mapper --> svc
deactivate mapper
svc --> isvc
deactivate svc
isvc --> ctrl
deactivate isvc
ctrl --> ictrl : Envia um código 201 (POST)
deactivate ctrl
ictrl --> route
deactivate ictrl
deactivate route



@enduml