@startuml sd
participant View as view
participant Controller as ctrl
participant Service as svc
participant Robo as model
participant MDGD as be

activate view
view -> ctrl : inhibitRobot()
activate ctrl
ctrl -> model : inhibitRobot(codigoRobo)
activate model
model --> ctrl : robot
deactivate model
ctrl -> svc: save(robo)
activate svc
svc -> be: PATCH robot {json}
activate be
be --> svc : Resposta HTTP
deactivate be
deactivate svc
alt sucesso 
svc --> ctrl : HTTP 200
ctrl --> view : Envia Mensagem
else insucesso
svc --> ctrl : HTTP 4xx / HTTP500
ctrl --> view : Envia Mensagem
end
deactivate view
deactivate ctrl
@enduml